spring.application.name=camelProject

diretorioEntrada = \entrada
diretorioSaida = \saida

xpathCnpjTransportadora = //ns:transp/ns:transporta/ns:CNPJ/text()
xpathTransportadora2 = //ns:transp/ns:transporta/ns:CNPJ[text()='2']
xpathPedido = //ns:infAdic/ns:obsCont[@xCampo='PEDIDO1']/ns:xTexto/text()

urlApiTransportadoraOLX = http://0.0.0.0:8080